package com.wooweather;

/**
 * Created by mostafa on 12/31/2015.
 */
public class ChooseCity {
        String AllCity[];

        public String[] getAllCity() {
                AllCity = new String[]{"Aalborg,Denmark" ,"Abbotsford,BC" , "Aberdeen_Prv_Gnd,MD" ,
                        "Aberdeen,ID" , "Aberdeen,MD" ,
                        "Aberdeen,Scotland" ,"Aberdeen,SD" , "Aberdeen,WA" , "Abilene,KS" ,
                        "Abilene,TX" , "Acapulco,Mexico" , "Accra,Ghana" ,
                        "Ada,MN" , "Adak,AK" , "Adams,MA" ,
                        "Addis_Ababa,Ethiopia" ,
                        "Adelaide,Australia" ,"Abu Dhabi,UAE",
                        "Aden,Yemen" , "Afton,OK" , "Afton,WY" ,
                        "Agana_NAS,Guam" ,"Agra,India", "Ahwahnee,CA" , "Aiken,SC" ,
                        "Ainsworth,NE" , "Ajo,AZ" , "Akron,OH" ,
                        "Al_Manamah,Bahrain" , "Alameda,CA" ,
                        "Alamo,NV" , "Alamogordo,NM" , "Albany,GA" , "Albany,NY" ,
                        "Albany,OR" , "Albion,ID" ,
                        "Albuquerque,NM" , "Alcoa,TN" , "Aldermaston,England" ,
                        "Alert,NWT" , "Alexander_City,AL" ,
                        "Alexandria,Egypt" , "Alexandria,LA" , "Alexandria,VA" ,
                        "Algiers,Algeria" , "Alhambra,CA" , "Alice_Springs,Austral" ,
                        "Allen_AAF,AK" , "Allentown,PA" ,
                        "Alliance,NE" , "Alpharetta,GA" , "Alpine,CA" ,
                        "Altenstadt,Germany" , "Altoona,PA" , "Amami_Island,Japan" ,
                        "Amarillo,TX" , "Ambler,AK" ,
                        "Amchitka,AK" , "American_Falls,ID" ,
                        "Ames,IA" ,
                        "Amherst,OH" ,
                        "Amilcar_Cabral,C._Ver" ,
                        "Amman,Jordan" ,
                        "Amsterdam,Neth" , "Anaconda,MT" , "Anaheim,CA" ,
                        "Anchorage,AK" ,
                        "Anderson_AFB,Guam" ,
                        "Anderson,IN" ,
                        "Anderson,SC" ,"Andorra la Vella,Andorra",

                        "Ankara,Turkey" , "Ann_Arbor,MI" , "Annapolis,MD" ,
                        "Annette_Is.,AK" , "Anniston,AL" , "Ansbach,Germany" ,
                        "Antlers,OK" , "Antalya,Turkey","Antofagasta,Chile" , "Antwerp,Belgium" ,
                        "Appleton,WI" , "Aqaba,Jordan" , "Arcade-Arden,CA" ,
                        "Ardmore,OK" , "Arese,Italy" , "Argyle,MN" , "Arica,Chile" ,
                        "Arkadelphia,AR" , "Arlington_Hts.,IL" , "Arlington,MA" , "Arlington,TX" ,
                        "Arlington,VA" , "Armour,SD" , "Arvada,CO" ,"Artvin,Turkey",
                        "Ash_Fork,AZ" , "Asheville,NC" , "Ashland,KS" , "Ashland,KY" ,
                        "Ashland,ME" ,
                        "Ashley,ND" , "Asmara,Ethiopia" , "Aspen,CO" , "Astoria,OR" ,
                        "Asuncion,Paraguay" , "Aswan,Egypt" ,
                        "Athens,GA" ,
                        "Athens,Greece" , "Athens,TN" , "Atkinson,NE" ,
                        "Atlanta,GA" , "Atlantic_City,NJ" ,
                        "Atmore,AL" , "Attleboro,MA" ,
                        "Auburn,AL" , "Auburn,ME" ,
                        "Auckland,New_Zealand" , "Augusta,AR" ,
                        "Augusta,GA" , "Augusta,ME" , "Aurora,CO",
                        "Aurora,IL", "Aurora,MN", "Austin,NV",
                        "Austin,TX", "Avalon,Australia", "Aviano,Italy",
                        "Avon,CT", "Ayase,Japan", "Aztec,NM",


                        "Babelthuap_Island" , "Bacolod,Philippines" , "Baden,Germany" ,
                        "Baghdad,Iraq" , "Bahrain" , "Baie-Comeau,PQ" ,
                        "Baker,MT" , "Bakersfield,CA" , "Balboa,Panama" ,
                        "Baldwin Park,CA" , "Bali" , "Baltimore,MD" ,
                        "Bamberg,Germany" , "Bandar_Abbass,Iran" , "Bandar_Lengeh,Iran" ,
                        "Bandirma,Turkey" , "Banff,AB" , "Bangalore,India" ,
                        "Bangkok,Thailand" , "Bangor,ME" , "Banjul,Gambia" ,
                        "Bar_Harbor,ME" , "Baraboo,WI" , "Barcelona,Spain" ,
                        "Barnesville,OH" , "Barranquilla,Colombia" , "Barre,VT" ,
                        "Barron,WI" , "Barrow,AK" , "Barstow,CA" ,
                        "Bartlesville,OK" , "Barton,VT" , "Basrah,Iran" ,
                        "Batesburg,SC" , "Baton_Rouge,LA" ,
                        "Battle_Creek,MI" , "Bay_City,MI" , "Bay_St._Louis,MS" ,
                        "Bayonne,NJ" , "Baytown,TX" , "Beach,ND" ,
                        "Beatty,NV" , "Beaufort,SC" , "Beaumont,TX" ,
                        "Beaver,UT" , "Beaverton,OR" , "Beckley,WV" ,
                        "Beijing,China" , "Beirut,Lebanon" , "Beja,Portugal" ,
                        "Belem,Brazil" , "Belen,NM" , "Belfast,N._Ireland" ,
                        "Belgrade,Serbia" , "Belize_City" , "Belleville,IL" ,
                        "Bellevue,NE" , "Bellevue,WA" , "Bellflower,CA" ,
                        "Bellingham,WA" , "Bellows_Falls,VT" ,
                        "Ben Guerir,Morocco" , "Bend,OR" , "Bennington,VT" ,
                        "Benton,AR" , "Bergen,Norway" , "Berkeley,CA" ,
                        "Berlin,Germany" , "Berlin,NH" ,
                        "Bermuda" , "Bern,Switzerland" ,

                        "Bethel,AK" , "Bethesda,MD" ,
                        "Bethlehem,PA" , "Bettendorf,IA" , "Bettles Field,AK" ,
                        "Biddeford,ME" , "Big_Delta,AK" , "Big_Lake,AK" ,
                        "Billings,MT" , "Biloxi,MS" , "Binghamton,NY" , "Birmingham,AL" ,
                        "Birmingham,England" , "Bismarck,ND" , "Bitburg,Germany" , "Blackpool,England" ,
                        "Blackwell,OK" , "Bloomfield,NJ" , "Bloomington,IL" ,
                        "Bloomington,IN" , "Bloomington,MN" , "Bluefield,WV" ,
                        "Bluff,UT" , "Boca Raton,FL" , "Boca Raton,FL" , "Bodo,Norway" ,
                        "Bogalusa,LA" , "Bogota,Colombia" , "Boise City,OK" ,
                        "Boise,ID" , "Bologna,Italy" , "Bombay,India" ,
                        "Bonn,Germany" , "Boone,NC" , "Booneville,KY" ,
                        "Bordeaux,France" , "Bordentown,NJ" , "Borinquen,PR" ,
                        "Boscobel,WI" ,
                        "Bossier City,LA" , "Boston,MA" , "Boulder_City,NV" ,
                        "Boulder Creek,CA" , "Boulder,CO" , "Bountiful,UT" ,
                        "Bowie,MD" , "Bowling_Green,KY" , "Bowman,ND" ,
                        "Bozeman,MT" , "Bradshaw_AAF,HI" , "Brandon,MB" ,
                        "Brandon,VT" , "Brasilia,Brazil" , "Brattleboro,VT" ,
                        "Bremen,Germany" , "Bremerton,WA" , "Brest,France" ,
                        "Bridgeport,CT" , "Bridgeton,NJ" , "Brilliant,OH" ,
                        "Brisbane,Australia" , "Bristol,CT" , "Bristol,England" ,
                        "Bristol,RI" , "Bristol,TN" , "Bristol,VT" ,
                        "Brize_Norton,England" , "Brockton,MA" , "Broken_Arrow,OK" ,
                        "Brookings,OR" , "Brookings,SD" , "Brookline,MA" ,
                        "Brooklyn Park,MN" , "Brookside Park,DE" , "Brownsville,TX" ,
                        "Brunswick,GA" , "Brunswick,ME" , "Brussels,Belgium" ,
                        "Bucharest,Romania" , "Buckeburg,Germany" , "Budapest,Hungary" ,
                        "Buena_Park,CA" , "Buenos_Aires,Argent" ,
                        "Buffalo,NY" , "Buffalo,WY" , "Burbank,CA" ,
                        "Burlington,CO" , "Burlington,CT" , "Burlington,IA" ,
                        "Burlington,NC" , "Burlington,VT" , "Burlington,WA" ,
                        "Burns,OR" , "Burwash,YT" , "Butte,MT" ,
                        "Butterworth,Malaysia","Burgas,Bulgaria",


                        "Cairo,Egypt" , "Calais,France" , "Calcutta,India" ,
                        "Caldwell,ID" , "Calgary,Alberta" , "Caliente,NV" ,
                        "Cambridge,England" , "Cambridge,MA" , "Cambridge,MD" ,
                        "Camden,NJ" , "Canberra,Australia" , "Cannes,France" ,
                        "Canoga Park,CA" , "Canton,China" , "Canton,OH" ,
                        "Cantonsville,MD" , "Cape_Canaveral,FL" , "Cape_Girardeau,MO" ,
                        "Cape May,NJ" , "Cape_Town,So_Africa" ,
                        "Caracas,Venezuela" , "Carbonado,WA" , "Carbondale,IL" ,
                        "Cardiff,Wales" , "Carlton,MN" , "Carmichael,CA" ,
                        "Carrizozo,NM" , "Carrollton,GA" , "Carson_City,NV" ,
                        "Carson,CA" , "Cartersville,GA" , "Cary,IL" ,"Cancun,Mexico",
                        "Casa_Grande,AZ" , "Casablanca,Morocco" , "Casper,WY" ,
                        "Castlerock,WA" , "Cave_Creek,AZ" , "Cayenne,Fr._Guiana" ,
                        "Cedar City,UT" , "Cedar_Falls,IA" , "Cedar_Rapids,IA" ,
                        "Central_Islip,NY" , "Centreville,MD" , "Cerritos,CA" ,
                        "Chagrin_Falls,OH" , "Champaign,IL" , "Chapel_Hill,NC" ,
                        "Charleston,SC" , "Charleston,WV" , "Charlevoix,PQ" ,
                        "Charlotte,NC" , "Charlottesville,VA" , "Charlottetown,PEI" ,
                        "Chatham,NB" , "Chattanooga,TN" , "Cheju,S._Korea" ,
                        "Cheltenham,PA" , "Chennai,India","Cheraw,SC" , "Cherbourg,France" ,
                        "Cherokee,OK" , "Chesapeake,VA" , "Chester,CT" ,
                        "Chester,PA" , "Cheyenne,WY" , "Chiang_Mai,Thailand" ,
                        "Chibougamau,PQ" , "Chicago,IL" , "Chiclayo,Peru" ,
                        "Chicopee,MA" , "Chignik,AK" , "Chillicothe,IL" ,
                        "Chillicothe,MO" , "Chillicothe,OH" , "Chino_Hills,CA" ,
                        "Chino,CA" , "Chinook,MT" , "Chitose,Japan" ,
                        "Chittagong,Bangladesh" , "Christchurch,N_Zealan" ,
                        "Chula_Vista,CA" , "Churchill,MB" , "Chuuk,Micronesia" ,
                        "Cicero,IL" , "Cincinnati,OH" , "Circle,AK" ,
                        "Circleville,OH" , "Claremont,NH" , "Clark,NJ" ,
                        "Clarksburg,WV" , "Clarksdale,MS" , "Clarksville,TN" ,
                        "Claymont,DE" , "Clear_Lake_City,TX" , "Clear,AK" ,
                        "Clearlake,CA" , "Clearwater,FL" , "Cleveland,OH" ,
                        "Cleveland,TN" , "Clifton,NJ" , "Clinton,IA" ,
                        "Clovis,NM" , "Cockeysville,MD" , "Cody,WY" ,
                        "Cold_Bay,AK" , "Cold_Lake,AB" , "College_Park,MD" , "Collegedale,TN" ,
                        "Cologne,Germany" , "Colombo,Sri_Lanka" , "Colon,Panama" ,
                        "Colorado_Springs,CO" , "Columbia_Stn.,OH" ,
                        "Columbia,MO" , "Columbia,SC" , "Columbia,TN" , "Columbus,GA" , "Columbus,MS" ,
                        "Columbus,NE" , "Columbus,OH" , "Columbus,OH" , "Columbus,OH" ,
                        "Comox,BC" , "Compton,CA" , "Concepcion,Chile" , "Concord,CA" ,
                        "Concord,NH" , "Condon,OR" , "Conway,AR" , "Conway,NH" , "Copenhagen,Denmark" ,
                        "Coralville,IA" , "Corbin,KY" , "Cordova,AK" ,
                        "Corinth,MS" , "Corning,IA" , "Corpus_Christi,TX" ,
                        "Cortez,CO" , "Corvallis,OR" , "Costa_Mesa,CA" ,
                        "Council_Bluffs,IA" , "Covington,KY" , "Cranbrook,BC" , "Cranford,NJ" ,
                        "Cranston,RI" , "Crawford,NE" , "Crestwood,KY" ,
                        "Crestwood,MO" , "Creve_Coeur,IL" , "Cripple_Creek,CO" , "Crocker,MO" ,
                        "Crofton,NE" , "Cubi_Point,Philippine" , "Culver_City,CA" ,
                        "Cumberland,MD" , "Cut_Bank,MT", "Dakar,Senegal" , "Dallas,TX" ,
                        "Dalsbruk,Finland" , "Daly_City,CA" , "Damascus,Syria" , "Danbury,CT" ,
                        "Danielson,CT" , "Danville,IA" , "Danville,VA" ,"Dammam,Saudi Arabia",
                        "Dar_es_Salaam,Tanzan" , "Darwin,Australia" , "Davenport,IA" ,
                        "Dayton,OH" , "Dayton,TN" , "Daytona_Beach,FL" ,
                        "Deadhorse,AK" , "Dearborn_Heights,MI" , "Dearborn,MI" , "Decataur,IL" ,
                        "Decimomannu,Italy" , "Dekalb,IL" , "Del_Rio,TX" ,
                        "Delavan,WI" , "Delhi,LA" , "Delta_Jct.,AK" , "Delta,UT" , "DeMotte,IN" ,
                        "Denali,AK" ,"Denpasar,Indonesia", "Denton,TX" , "Denver,CO" ,
                        "Derby,CT" , "Derby,England" , "Derry,NH" ,
                        "Des_Moines,IA" , "Des_Plaines,IL" , "Desiderio_AAF,S._Kore" ,
                        "Detroit,MI" , "Devils_Lake,ND" , "Dhahran,Saudi Arabia" , "Diamond_Bar,CA" ,
                        "Diamond_Springs,CA" , "Dickinson,ND" , "Dickinson,TX" ,"Djerba,Tunisia",

                        "Dijon,France" , "Dillingham,HI" , "Dillon,MT" , "Dillon,SC" , "Diyarbakir,Turkey" ,
                        "Djakarta,Indonesia" , "Dodge_City,KS" , "Doha,Qatar" , "Dortmund,Germany" ,
                        "Dothan,AL" , "Douala,Cameroon" , "Dover_AFB,DE" ,
                        "Dover,DE" , "Dover,England" , "Dover,FL" , "Dover,NH" ,
                        "Downey,CA" , "Dryden,ON" , "Dubai,UAE." , "Dublin,Ireland" ,
                        "Dubrovnik,Croatia" , "Dubuque,IA" , "Duluth,MN" ,
                        "Dundalk,MD" , "Dunedin,New Zealand" , "Dunlap,IA" ,
                        "Durango,CO" , "Durham,NC" , "Durham,NC" ,
                        "Dusseldorf,Germany" , "Dutch_Harbor,AK" , "E._Brunswick,NJ" ,
                        "E._Lansing,MI" ,
                        "E._Las_Vegas,NV" ,
                        "E._Los_Angeles,CA" ,
                        "E._St._Louis,IL" ,
                        "E._Stroudsburg,PA" ,
                        "E._Wenatchee,WA" ,
                        "Eagan,MN" ,
                        "Eagle_River,AK" ,
                        "Eagle,AK" ,
                        "East_Boston,MA" ,
                        "East_Orange,NJ" ,
                        "East_Point,GA" ,


                        "Eastampton,NJ" ,
                        "Eatonton,GA" ,
                        "Eau_Claire,WI" ,
                        "Edina,MN" ,
                        "Edinburgh,Scotland" ,
                        "Edmond,OK" ,
                        "Edmonds,WA" ,
                        "Edmonton,AB" ,
                        "Edirne,Turkey",
                        "Edmundston,NB" ,
                        "Edna,TX" ,
                        "Edwards_AFB,CA" ,
                        "Efate,Vanuatu" ,
                        "Effingham,IL" ,
                        "Eielson_AFB,AK" ,
                        "El_Cajon,CA" ,
                        "El_Dorado,AR" ,
                        "El_Mirage,AZ" ,
                        "El_Monte,CA" ,
                        "El_Paso,TX" ,
                        "Eldorado,IL" ,
                        "Eldridge,IA" ,
                        "Elgin_AFB,FL" ,
                        "Elgin,IL" ,
                        "Elizabeth_City,NC" ,
                        "Elizabeth,NJ" ,
                        "Elizabethtown,KY" ,
                        "Elk_City,OK" ,
                        "Elk_Point,SD" ,
                        "Elk_River,ID" ,
                        "Elkhart,IN" ,
                        "Elkins,WV" ,
                        "Elko,NV" ,
                        "Ellsworth_AFB,SD" ,
                        "Elmira,NY" ,
                        "Elsmere,DE" ,
                        "Elverson,PA" ,
                        "Elyria,OH" ,
                        "Enfield,CT" ,
                        "Englewood,CO" ,
                        "Enid,OK" ,
                        "Entebbe,Uganda" ,
                        "Ephrata,PA" ,
                        "Erding,Germany" ,
                        "Erfurt,Germany" ,
                        "Erie,PA" ,
                        "Escondido,CA" ,
                        "Esfahan,Iran" ,
                        "Essex_Junction,VT" ,
                        "Euclid,OH" ,
                        "Eudora,AR" ,
                        "Eugene,OR" ,
                        "Eugene,OR" ,
                        "Eureka,CA" ,
                        "Eureka,NV" ,
                        "Eureka,UT" ,
                        "Evanston,IL" ,
                        "Evanston,WY" ,
                        "Evansville,IN" ,
                        "Everett,WA" ,
                        "Evergreen,CO" ,
                        "Ewa,HI" ,
                        "Exeter,NH" ,

                        "Fair Haven,VT" ,
                        "Fairbanks,AK" ,
                        "Fairfax,MN" ,
                        "Fairfax,SC" ,
                        "Fairfield,CA" ,
                        "Fairfield,CT" ,
                        "Fairmont,WV" ,
                        "Faith,SD" ,
                        "Falcon,CO" ,
                        "Fall_River,MA" ,
                        "Fallon,NV" ,
                        "Falmouth,KY" ,
                        "Fargo,ND" ,
                        "Farmington,NM" ,
                        "Farnborough,England" ,
                        "Fayetteville,AR" ,
                        "Fayetteville,NC" ,
                        "Ferriday,LA" ,
                        "Finningley,England" ,
                        "Fisher,LA" ,
                        "Fitchburg,MA" ,
                        "Flagstaff,AZ" ,
                        "Flint,MI" ,
                        "Florala,AL" ,
                        "Florence,AL" ,
                        "Florence,SC" ,
                        "Florence,Italy",
                        "Florissant,MO" ,
                        "Flower_Mound,TX" ,
                        "Folsom,NM" ,
                        "Fond du Lac,WI" ,
                        "Ford Island,HI" ,
                        "Forrest City,AR" ,
                        "Forsyth,MT" ,
                        "Fort Collins,CO" ,
                        "Fort Dodge,IA" ,
                        "Fort Greely,AK" ,
                        "Fort Lauderdale,FL" ,
                        "Fort McMurray,AB" ,
                        "Fort McPherson,NWT" ,
                        "Fort Myers,FL" ,
                        "Fort Nelson,BC" ,
                        "Fort Payne,AL" ,
                        "Fort Richardson,AK" ,
                        "Fort Riley,KS" ,
                        "Fort Salonga,NY" ,
                        "Fort Scott,KS" ,
                        "Fort Simpson,NWT" ,
                        "Fort Smith,AR" ,
                        "Fort Yukon,AK" ,
                        "Fountain Valley,CA" ,
                        "Framingham,MA" ,
                        "Frankfort,KY" ,
                        "Frankfurt,Germany" ,
                        "Franklin,NH" ,
                        "Franklin,TN" ,
                        "Frederick,MD" ,
                        "Fredericksburg,VA" ,
                        "Fredericktown,MO" ,
                        "Fredericton,NB" ,
                        "Freehold,NJ" ,
                        "Freeport,Bahamas" ,
                        "Freiburg,Germany" ,
                        "Fremont,CA" ,
                        "Fremont,NE" ,
                        "Fresno,CA" ,
                        "Fruitland Park,FL" ,
                        "Ft._Myers,FL" ,
                        "Ft._Wayne,IN" ,
                        "Ft._Worth,TX" ,
                        "Fukuoka,Japan" ,
                        "Fullerton,CA" ,
                        "Funchal,Madeira_Is" ,
                        "Furth,Germany" ,



                        "Gadsden,AL" ,
                        "Gaillac,France" ,
                        "Gainesville,FL" ,
                        "Gainesville,GA" ,
                        "Gaithersburg,MD" ,
                        "Galena,AK" ,
                        "Gallup,NM" ,
                        "Galveston,TX" ,
                        "Gander,Nfld" ,
                        "Garden City,KS" ,
                        "Garden Grove,CA" ,
                        "Garland,TX" ,
                        "Garland,UT" ,
                        "Garrison,ND" ,
                        "Gars am Inn,Germany" ,
                        "Gary,IN" ,
                        "Gaspe,PQ" ,
                        "Gassaway,WV" ,
                        "Gastonia,NC" ,
                        "Gdansk,Poland" ,
                        "Geilenkirchen,Germany" ,
                        "Geneva,Switz." ,
                        "Genoa,Italy" ,
                        "Georgetown,DE" ,
                        "Georgetown,Guyana" ,
                        "Gera,Germany" ,

                        "Gila Bend,AZ" ,
                        "Gillette,WY" ,
                        "Glasgow,KY" ,
                        "Glasgow,Scotland" ,
                        "Glendale,AZ" ,
                        "Glendale,CA" ,
                        "Glendora,CA" ,
                        "Glenns Ferry,ID" ,
                        "Glens Falls,NY" ,
                        "Glenwood Springs,CO" ,
                        "Glenwood,MN" ,
                        "Godthab,Greenland" ,
                        "Goldfield,NV" ,
                        "Goldsboro,NC" ,
                        "Goldstone,CA" ,
                        "Goose Bay,Nfld." ,
                        "Goose Creek,SC" ,
                        "Gorham,ME" ,
                        "Granada Hills,CA" ,

                        "Grand Forks,ND" ,
                        "Grand Island,NE" ,
                        "Grand Junction,CO" ,
                        "Grand Prairie,TX" ,
                        "Grand Rapids,MI" ,

                        "Granger,WY" ,
                        "Grangeville,ID" ,
                        "Granite Falls,MN" ,
                        "Grants Pass,OR" ,
                        "Grass Valley,CA" ,
                        "Great Falls,MT" ,
                        "Great Falls,SC" ,
                        "Greeley,CO" ,
                        "Green Bay,WI" ,
                        "Green River,UT" ,
                        "Green River,WY" ,
                        "Greenbelt,MD" ,
                        "Greensboro,NC" ,
                        "Greenville,ME" ,
                        "Greenville,MS" ,
                        "Greenville,SC" ,
                        "Greenville,TN" ,
                        "Greenwich Obs,England" ,
                        "Greenwich,CT" ,
                        "Greenwood,MS" ,
                        "Greenwood,SC" ,
                        "Grenoble,France" ,
                        "Gresham,OR" ,
                        "Grissom AFB,IN" ,
                        "Groton,SD" ,
                        "Groveton,NH" ,
                        "Guantanamo Bay,Cuba" ,
                        "Guatemala City" ,
                        "Guayaquil,Ecuador" ,
                        "Guelph,ON" ,
                        "Gulfport,MS" ,
                        "Gulkana,AK" ,
                        "Gutersloh,Germany" ,
                        "Guilin,China",
                        "Guangzhou,China",
                        "Guthrie,OK" ,
                        "Hagerstown,MD" ,
                        "Haiku,HI" ,
                        "Hailey,ID" ,
                        "Haines,AK" ,
                        "Halifax,NS" ,
                        "Hamburg,Germany" ,
                        "Hamden,CT" ,
                        "Hamilton,OH" ,
                        "Hamilton,ON" ,
                        "Hammond,IN" ,
                        "Hampton,VA" ,
                        "Hanoi,Vietnam",
                        "Hana,HI" ,
                        "Hancock,MI" ,
                        "Hankinson,ND" ,
                        "Hannah,ND" ,
                        "Hannibal,MO" ,
                        "Hannover,Germany" ,
                        "Hao_AB,Fr._Polynesia" ,
                        "Harper Woods,MI" ,
                        "Harpers Ferry,WV" ,
                        "Harrington,DE" ,
                        "Harrisburg,PA" ,
                        "Harrisburg,SD" ,
                        "Harrison,AR" ,
                        "Harrisonburg,VA" ,
                        "Hartford,CT" ,
                        "Hangzhou,China",
                        "Harvey,ND" ,
                        "Hastings,NE" ,
                        "Hat_Yai,Thailand" ,
                        "Hattiesburg,MS" ,
                        "Hauula,HI" ,
                        "Havana,Cuba" ,
                        "Havre,MT" ,
                        "Hawthorne,CA" ,
                        "Hawthorne,NV" ,
                        "Hayward,CA" ,
                        "Hazard,KY" ,
                        "Helena,MT" ,
                        "Helgoland,Germany" ,
                        "Helsinki,Finland" ,
                        "Henderson,KY" ,
                        "Henderson,NV" ,
                        "Hendersonville,TN" ,
                        "Herndon,VA" ,
                        "Hialeah,FL" ,
                        "Hickory,NC" ,
                        "High_Point,NC" ,
                        "Highland Lakes,NJ" ,
                        "Highmore,SD" ,
                        "Hill City,MN" ,
                        "Hillsboro,ND" ,
                        "Hillsboro,OR" ,
                        "Hilo,HI" ,
                        "Hinton,WV" ,
                        "Hobbs,NM" ,
                        "Holbrook,AZ" ,
                        "Hollis Hills,NY" ,
                        "Holliston,MA" ,
                        "Holly Springs,MS" ,
                        "Hollywood,CA" ,
                        "Hollywood,FL" ,
                        "Holyoke,MA" ,
                        "Homer,AK" ,
                        "Hong_Kong" ,
                        "Honiara,Guadalcanal" ,
                        "Honington,England" ,
                        "Honolulu,HI" ,
                        "Hooker,OK" ,
                        "Hooper Bay,AK" ,
                        "Hopkinsville,KY" ,
                        "Hot Springs Nat Pk,AR" ,
                        "Houma,LA" ,
                        "Houston,TX" ,
                        "Humboldt,NE" ,
                        "Huntington_Beach,CA" ,
                        "Huntington_Station,NY" ,
                        "Huntington,WV" ,
                        "Huntsville,AL" ,
                        "Hurley,WI" ,
                        "Huron,SD" ,
                        "Hutchinson,KS" ,
                        "Hutchinson,MN" ,
                        "Hyltebruk,Sweden",

                        "Idaho_Falls,ID" ,
                        "Incirlik,Turkey" ,
                        "Independence,KS" ,
                        "Independence,MO" ,
                        "Indianapolis,IN" ,
                        "Ine,Marshall_Is" ,
                        "Inglewood,CA" ,
                        "Innsbruck,Austria" ,
                        "Inuvik,NWT" ,
                        "Invercargill,New_Zeal" ,
                        "Iowa_City,IA" ,
                        "Ipswich,Australia" ,
                        "Iqaluit,NWT" ,
                        "Iron River,MI" ,
                        "Irvine,CA" ,
                        "Irving,TX" ,
                        "Irvington,NJ" ,
                        "Islamabad,Pakistan" ,

                        "Istanbul,Turkey" ,
                        "Istrana,Italy" ,
                        "Jackson,MI" ,
                        "Jackson,MS" ,
                        "Jackson,TN" ,
                        "Jacksonville,AR" ,
                        "Jacksonville,FL" ,
                        "Jakarta,Indonesia" ,
                        "Jaluit,Marshall_Is." ,
                        "Jamestown,ND" ,
                        "Janesville,WI" ,

                        "Jasper,AB" ,
                        "Jaipur,India",
                        "Jatiluhur,Indonesia" ,
                        "Jeddah,Saudia Arabia" ,
                        "Jefferson City,MO" ,
                        "Jensen Beach,FL" ,
                        "Jersey City,NJ" ,
                        "Jeju,South Korea",
                        "Jerusalem,Israel" ,
                        "Johannesburg,S_Africa" ,
                        "Johnson City,TN" ,


                        "Johnstown,PA" ,
                        "Joliet,IL" ,
                        "Jonesboro,AR" ,
                        "Joplin,MO" ,
                        "Julian,CA" ,
                        "Juneau,AK" ,

                        "Kabul,Afghanistan" ,
                        "Kaena_Point,HI" ,
                        "Kahului,HI" ,
                        "Kailua Kona,HI" ,
                        "Kalamazoo,MI" ,
                        "Kalapana,HI" ,
                        "Kalaupapa,HI" ,
                        "Kalispell,MT" ,
                        "Kamloops,BC" ,
                        "Kamuela,HI" ,
                        "Kanab,UT" ,
                        "Kaneohe Bay,HI" ,
                        "Krakow,Poland",
                        "Kankakee,IL" ,
                        "Kannapolis,NC" ,
                        "Kano,Nigeria" ,
                        "Kansas City,KS" ,
                        "Kansas City,MO" ,
                        "Kapaa,HI" ,
                        "Kapalua,HI" ,
                        "Kapuskasing,ON" ,
                        "Karachi,Pakistan" ,
                        "Kassel,Germany" ,
                        "Kathmandu,Nepal" ,
                        "Kaunakakai,HI" ,
                        "Keahole,HI" ,
                        "Kearney,NE" ,
                        "Keene,NH" ,
                        "Keflavik,Iceland" ,
                        "Kekaha,HI" ,
                        "Kelso,WA" ,
                        "Kenai,AK" ,
                        "Kennebunk,ME" ,
                        "Kenner,LA" ,
                        "Kenora,ON" ,
                        "Kenosha,WI" ,
                        "Ketchikan,AK" ,
                        "Kettering,OH" ,
                        "Khania,Greece" ,
                        "Khartoum,Sudan" ,
                        "Kiel,Germany" ,
                        "Kiev,Ukraine",
                        "Kili,Marshall_Is." ,
                        "Kimball,NE" ,
                        "King George,VA" ,
                        "King Salmon,AK" ,
                        "Kingman,AZ" ,
                        "Kings Beach,Australia" ,
                        "Kingsport,TN" ,
                        "Kingston,Jamaica" ,
                        "Kingston,ON" ,
                        "Kinshasa,Zaire" ,
                        "Kissimmee,FL" ,
                        "Kit Carson,CO" ,
                        "Kitchener,ON" ,
                        "Klamath Falls,OR" ,
                        "Knightdale,NC" ,
                        "Knoxville,TN" ,
                        "Kodiak,AK" ,
                        "Kohala,HI" ,
                        "Koko_Head,HI" ,
                        "Kokomo,IN" ,
                        "Koln,Germany" ,
                        "Koloa,HI" ,
                        "Kona,HI" ,
                        "Korat,Thailand" ,
                        "Kosrae,Micronesia" ,
                        "Kota Kinabalu,Malaysi" ,
                        "Kotzebue,AK" ,
                        "Kuala Lumpur,Malaysia" ,
                        "Kuching,Malaysia" ,

                        "Kuwait" ,
                        "Kyoto,Japan" ,
                        "Krabi,Thailand",
                        "La Crosse,WI" ,
                        "La Grande,OR" ,
                        "La Grange,GA" ,
                        "La Mesa,CA" ,
                        "La Paz,Bolivia" ,
                        "La Rochelle,France" ,
                        "La Verne,CA" ,
                        "Laconia,NH" ,
                        "Lafayette,IN" ,
                        "Lafayette,LA" ,
                        "Lagos,Nigeria" ,
                        "Lahore,Pakistan" ,
                        "Lahr,Germany" ,
                        "Lajes,Azores" ,
                        "Lake Charles,LA" ,
                        "Lake City,FL" ,
                        "Lake Oswego,OR" ,
                        "Lake Villa,IL" ,
                        "Lake Village,AR" ,
                        "Lakeland,FL" ,
                        "Lakewood,CA" ,
                        "Lakewood,CO" ,
                        "Lakewood,OH" ,
                        "Lakota,ND" ,
                        "Lamar,CO" ,
                        "Lanai City,HI" ,
                        "Lancaster,NH" ,
                        "Lancaster,PA" ,
                        "Lander,WY" ,
                        "Lansing,MI" ,
                        "LaPeer,MI" ,
                        "Laramie,WY" ,
                        "Laredo,TX" ,
                        "Largo,FL" ,
                        "Las Cruces,NM" ,
                        "Las Palmas,Canary_Is." ,
                        "Las Vegas,NV" ,
                        "Latham,Australia" ,
                        "Laurel,DE" ,
                        "Laurel,MD" ,
                        "Laurel,MS" ,
                        "Laval,PQ" ,
                        "Lawrence,KS" ,
                        "Lawrence,MA" ,
                        "Lawton,OK" ,
                        "Layton,UT" ,
                        "Le Havre,France" ,
                        "Learmonth,Australia" ,
                        "Leavenworth,KS" ,
                        "Leavenworth,WA" ,
                        "Lebanon,KY" ,
                        "Lebanon,MO" ,
                        "Lebanon,NH" ,
                        "Lechfeld_AFB,BY,Germ" ,
                        "Leck,Germany" ,
                        "Leeds,England" ,
                        "Leipzig,Germany" ,
                        "Lemmon,SD" ,
                        "Leningrad,Russia" ,
                        "Lethbridge,AB" ,
                        "Lewes,DE" ,
                        "Lewisburg,WV" ,
                        "Lewiston,ID" ,
                        "Lewiston,ME" ,
                        "Lewiston,NY" ,
                        "Lewistown,MT" ,
                        "Lexington,KY" ,
                        "Lhasa,Tibet" ,
                        "Libreville,Gabon" ,
                        "Lihue,HI" ,
                        "Lima,OH" ,
                        "Lima,Peru" ,
                        "Lincoln_Muni,NE" ,
                        "Lincoln,KS" ,
                        "Lincoln,ME" ,
                        "Lincoln,NE" ,
                        "Lindenhurst,NY" ,
                        "Linz,Austria" ,
                        "Lisbon,ND" ,
                        "Lisbon,Portugal" ,
                        "Little Rock,AR" ,
                        "Littleton,NH" ,
                        "Liverpool,England" ,
                        "Livingston,AL" ,
                        "Livingston,MT" ,
                        "Livonia,MI" ,
                        "Lockwood_Valley,CA" ,
                        "Logan,UT" ,
                        "Lolo,MT" ,
                        "Lompoc,CA" ,
                        "London,England" ,
                        "London,ON" ,
                        "Long Beach,CA" ,
                        "Longview,TX" ,
                        "Longview,WA" ,
                        "Lorain,OH" ,
                        "Lordsburg,NM" ,
                        "Los Alamos,NM" ,
                        "Los Altos_Hills,CA" ,
                        "Los Angeles,CA" ,
                        "Louisville,GA" ,
                        "Louisville,KY" ,

                        "Loveland,CO" ,
                        "Lovelock,NV" ,
                        "Lowell,MA" ,
                        "Lubbock,TX" ,
                        "Ludwigshafen,Germany" ,
                        "Lusaka,Zambia" ,
                        "Luxembourg City" ,
                        "Lynchburg,VA" ,
                        "Lynden,WA" ,
                        "Lynn Haven,FL" ,
                        "Lynn,MA" ,
                        "Lyon,France" ,
                        "Mackay,ID" ,
                        "Macon,GA" ,
                        "Madelia,MN" ,
                        "Madison,AL" ,
                        "Madison,SD" ,
                        "Madison,WI" ,
                        "Madison,WI" ,
                        "Madras,India" ,
                        "Madrid,Spain" ,
                        "Magdalena,NM" ,
                        "Magnolia,AR" ,
                        "Maiquetia,Venezuela" ,
                        "Majuro,Marshall_Is" ,
                        "Malden,MA" ,
                        "Male,Maldive_Is." ,
                        "Maloelap,Marshall_Is." ,
                        "Malone,NY" ,
                        "Malta",
                        "Managua,Nicaragua" ,
                        "Manaus,Brazil" ,
                        "Manchester,CT" ,
                        "Manchester,England" ,
                        "Manchester,NH" ,
                        "Mandalay,Myanmar" ,
                        "Mandan,ND" ,
                        "Mangum,OK" ,
                        "Manhattan Beach,CA" ,
                        "Manhattan,KS" ,
                        "Manila,Philippines" ,
                        "Manitowoc,WI" ,
                        "Mannheim,Germany" ,
                        "Mansfield,OH" ,
                        "Manton,CA" ,
                        "Mantorville,MN" ,
                        "Marietta,GA" ,
                        "Marion,VA" ,
                        "Marrakech,Morocco",
                        "Marlton,NJ" ,
                        "Marquette,MI" ,
                        "Marseille,France" ,
                        "Marshall,TX" ,
                        "Martinsburg,WV" ,
                        "Martinsville,VA" ,
                        "Mashpee,MA" ,
                        "Mason City,IA" ,
                        "Mauldin,SC" ,
                        "Mayaguez,PR" ,
                        "Maysville,KY" ,
                        "Mc Alester,OK" ,
                        "Mc Cook,NE" ,
                        "Mc Gill,NV" ,
                        "Mc Nary,LA" ,
                        "McAllen,TX" ,
                        "McGrath,AK" ,
                        "McKeesport,PA" ,
                        "McNary,AZ" ,
                        "Mecca,Saudi Arabia",
                        "Medford,MA" ,
                        "Marne La Vallee,France",
                        "Medford,OR" ,
                        "Medicine_Hat,AB" ,
                        "Melbourne,Australia" ,
                        "Melbourne,FL" ,
                        "Melksham,England" ,
                        "Melrose Park,IL" ,
                        "Memphis,TN" ,
                        "Mena,AR" ,
                        "Meredith,NH" ,
                        "Meriden,CT" ,
                        "Meridian,MS" ,
                        "Meridianville,AL" ,
                        "Merrimack,NH" ,
                        "Merritt Island,FL" ,
                        "Mesa,AZ" ,
                        "Mesquite,TX" ,
                        "Metairie,LA" ,
                        "Mexico City,Mexico" ,
                        "Mexico,MO" ,
                        "Miami Beach,FL" ,
                        "Miami,FL" ,
                        "Midas,NV" ,
                        "Middlebury,VT" ,
                        "Middletown,DE" ,
                        "Midland,TX" ,
                        "Midwest City,OK" ,
                        "Milan,Italy" ,
                        "Milbank,SD" ,
                        "Milford,CT" ,
                        "Milford,DE" ,
                        "Milford,NH" ,
                        "Milford,UT" ,
                        "Mili,Marshall_Is." ,
                        "Milledgeville,GA" ,
                        "Miller,SD" ,
                        "Millinocket,ME" ,
                        "Millville,NJ" ,
                        "Milpitas,CA" ,
                        "Milwaukee,WI" ,
                        "Mine Hill,NJ" ,
                        "Minneapolis,MN" ,
                        "Minnetonka,MN" ,
                        "Minot,ND" ,
                        "Miramar NAS,CA" ,
                        "Miramar,FL" ,
                        "Mishawaka,IN" ,
                        "Mississauga,ON" ,
                        "Missoula,MT" ,
                        "Mitchell,SD" ,
                        "Mobile,AL" ,
                        "Mobridge,SD" ,
                        "Modesto,CA" ,
                        "Moenkopi,AZ" ,
                        "Moline,IL" ,
                        "Molokai,HI" ,
                        "Monaco" ,
                        "Moncton,NB" ,
                        "Monroe,LA" ,
                        "Monrovia,Liberia" ,
                        "Mont-Joli,PQ" ,
                        "Montebello,CA" ,
                        "Montego Bay,Jamaica" ,
                        "Monterey Park,CA" ,
                        "Monterey,CA" ,
                        "Montevideo,Uruguay" ,
                        "Montgomery,AL" ,
                        "Monticello,IN" ,
                        "Monticello,ME" ,
                        "Monticello,UT" ,
                        "Montour Falls,NY" ,
                        "Montpelier,IN" ,
                        "Montpelier,VT" ,
                        "Montpellier,France" ,
                        "Montreal,PQ" ,
                        "Moore,OK" ,
                        "Moose Jaw,Sask." ,
                        "Morehead,KY" ,
                        "Morgan City,LA" ,
                        "Morgantown,WV" ,
                        "Moron AB,Spain" ,
                        "Morristown,NJ" ,
                        "Morristown,TN" ,
                        "Morrow,GA" ,
                        "Moscow,ID" ,
                        "Moscow,Russia" ,
                        "Moses Lake,WA" ,
                        "Mount Erebus,Antarcti" ,
                        "Mount Hopkins,AZ" ,
                        "Mount Vernon,NY" ,
                        "Mountain Brook,AL" ,
                        "Mountain_Home_AFB,ID" ,
                        "Mountain View,CA" ,
                        "Mountain View,MO" ,
                        "Muncie,IN" ,
                        "Muncy,PA" ,
                        "Mugla,Turkey",
                        "Mumbai,India",
                        "Munich,Germany" ,
                        "Murfreesboro,TN" ,
                        "Murray,UT" ,
                        "Muskegon,MI" ,
                        "Muskogee,OK" ,
                        "Myrtle_Beach,SC",
                        "N'djamina,Chad" ,
                        "N._Bellmore,NY" ,
                        "N._Cape_May,NJ" ,
                        "N._Charleston,SC" ,
                        "N._Hollywood,CA" ,
                        "Las Vegas,NV" ,
                        "N._Little_Rock,AR" ,
                        "Naalehu,HI" ,
                        "Nagasaki,Japan" ,
                        "Nagoya,Japan" ,
                        "Nagpur,India" ,
                        "Nairobi,Kenya" ,
                        "Namorik,Marshall_Is." ,
                        "Nampa,ID" ,
                        "Nandi,Fiji" ,
                        "Napa,CA" ,
                        "Naperville,IL" ,
                        "Naples,FL" ,
                        "Naples,Italy" ,
                        "Nashua,NH" ,
                        "Nashville,TN" ,
                        "Nassau,Bahamas" ,
                        "Natal,Brazil" ,
                        "Natchez,MS" ,
                        "Needles,CA" ,
                        "Nellis_AFB,NV" ,
                        "Nenana,AK" ,
                        "Neponsit,NY" ,
                        "Nevada,MO" ,
                        "New Albany,IN" ,
                        "New Bedford,MA" ,
                        "New Britian,CT" ,
                        "New Brunswick,NJ" ,
                        "New Carrollton,MD" ,
                        "New Castle,Australia" ,
                        "New Castle,DE" ,
                        "New Castle,IN" ,
                        "New Castle,PA" ,
                        "New Delhi,India" ,
                        "New Hampton,IA" ,
                        "New Hartford,CT" ,
                        "New Haven,CT" ,
                        "New Iberia,LA" ,
                        "New London,CT" ,
                        "New Meadows,ID" ,
                        "New Orleans,LA" ,
                        "New Rochelle,NY" ,
                        "New Rockford,ND" ,
                        "New Washoe City,CA" ,
                        "New York,NY" ,
                        "Newark,DE" ,
                        "Newark,NJ" ,
                        "Newcastle,England" ,
                        "Newell,SD" ,
                        "Newport_Beach,CA" ,
                        "Newport_News,VA" ,
                        "Newport,KY" ,
                        "Newport,NH" ,
                        "Newport,OR" ,
                        "Newport,RI" ,
                        "Newport,VT" ,
                        "Newton,MA" ,
                        "Newton,NJ" ,
                        "Niagara alls,NY" ,
                        "Nice,France" ,
                        "Nicosia,Cyprus" ,
                        "Nitro,WV" ,
                        "Nogales,AZ" ,
                        "Nome,AK" ,
                        "Norco,CA" ,
                        "Norfolk,NE" ,
                        "Norfolk,VA" ,
                        "Norman,OK" ,
                        "North Bay,ON" ,
                        "North Olmstead,OH" ,
                        "North Platte,NE" ,
                        "Northfield,MN" ,
                        "Northport,WA" ,
                        "Northrop_Strip,NM" ,
                        "Northway,AK" ,
                        "Norton,KS" ,
                        "Norton,VA" ,
                        "Norwalk,CA" ,
                        "Norwalk,CT" ,
                        "Norway,ME" ,
                        "Nottingham,England" ,
                        "Nouan,France" ,
                        "Noumea,New Caledonia" ,
                        "Novi,MI" ,
                        "Nurnberg,BY,Germany",
                        "Oak Park,IL" ,
                        "Oak Ridge,TN" ,
                        "Oakfield,ME" ,
                        "Oakland,CA" ,
                        "Oakley,KS" ,
                        "Oberlin,OH" ,
                        "Oberpfaffenhofen,Germ" ,
                        "Ocala,FL" ,
                        "Ocean City,MD" ,
                        "Ocean Grove,NJ" ,
                        "Oceanside,CA" ,
                        "Odessa,TX" ,
                        "Ogallala,NE" ,
                        "Ogden,UT" ,
                        "Ohakea,New Zealand" ,
                        "Okinawa,Japan" ,
                        "Oklahoma City,OK" ,
                        "Olathe,KS" ,
                        "Oldendorf,Germany" ,
                        "Olean,NY" ,
                        "Olympia,WA" ,
                        "Omaha,NE" ,
                        "Ontario,CA" ,
                        "Oostende,Belgium" ,
                        "Opelika,AL" ,
                        "Opheim,MT" ,
                        "Oran,Algeria" ,
                        "Orange Park,FL" ,
                        "Orange,CA" ,
                        "Orange,CT" ,
                        "Orangeburg,SC" ,
                        "Orem,UT" ,
                        "Orlando,FL" ,
                        "Orleans,France" ,
                        "Osaka,Japan" ,
                        "Osborne,KS" ,
                        "Oshkosh,WI" ,
                        "Oslo,Norway" ,
                        "Ottawa,ON" ,
                        "Ottumwa,IA" ,
                        "Overland Park,KS" ,
                        "Owensboro,KY" ,
                        "Oxford,MS" ,
                        "Oxford,NC" ,
                        "Oxnard,CA" ,
                        "Ozark,AR" ,
                        "Paauilo,HI" ,
                        "Pacific_Beach,CA" ,
                        "Pacific,MO" ,
                        "Paducah,KY" ,

                        "Pago_Pago,Samoa" ,
                        "Palembang,Indonesia" ,
                        "Palm_City,FL" ,
                        "Palmdale,CA" ,
                        "Palmer,AK" ,
                        "Palo_Alto,CA" ,
                        "Panama City,FL" ,
                        "Panama City,Panama" ,
                        "Papeete,Tahiti" ,
                        "Paradise,NV" ,
                        "Paris,France" ,
                        "Paris,IL" ,
                        "Park Rapids,MN" ,
                        "Park View,NM" ,
                        "Parkersburg,WV" ,
                        "Parma,OH" ,
                        "Parsons,WV" ,
                        "Pasadena,CA" ,
                        "Pasadena,TX" ,
                        "Pascagoula,MS" ,
                        "Paterson,NJ" ,
                        "Pawtucket,RI" ,
                        "Peace River,AB" ,
                        "Pearce,Australia" ,
                        "Pembina,ND" ,
                        "Penang,Malaysia" ,
                        "Pendleton,OR" ,
                        "Pensacola,FL" ,
                        "Peoria,IL" ,
                        "Perth Amboy,NJ" ,
                        "Perth,Australia" ,
                        "Peru,IL" ,
                        "Peshawar,Pakistan" ,
                        "Petersburg,AK" ,
                        "Pattaya,Thailand",
                        "Petersburg,VA" ,
                        "Phenix City,AL" ,
                        "Philadelphia,PA" ,
                        "Philip,SD" ,
                        "Phoenix,AZ" ,
                        "Phuket,Thailand" ,
                        "Picayune,MS" ,
                        "Pico_Rivera,CA" ,
                        "Pierce,NE" ,
                        "Pierre,SD" ,
                        "Pilot_Hill,CA" ,
                        "Pine_Bluff,AR" ,
                        "Pine_City,MN" ,
                        "Pittsburgh,PA" ,
                        "Pittsfield,MA" ,
                        "Placerville,CA" ,
                        "Plainfield,NJ" ,
                        "Plaisance,Mauritius" ,
                        "Plano,TX" ,
                        "Plattsburgh_AFB,NY" ,
                        "Plattsburgh,NY" ,
                        "Plymouth,MA" ,
                        "Plymouth,MN" ,
                        "Plymouth,NH" ,
                        "Pocatello,ID" ,
                        "Pocomoke_City,MD" ,
                        "Pohnpei,Micronesia" ,
                        "Point_Hope,AK" ,
                        "Polson,MT" ,
                        "Pomona,CA" ,
                        "Pompano_Beach,FL" ,
                        "Ponca City,OK" ,
                        "Ponce,PR" ,
                        "Pontiac,MI" ,
                        "Poplar Bluff,MO" ,
                        "Poplar,MT" ,
                        "Port Allen,HI" ,
                        "Port Arthur,TX" ,
                        "Port Huron,MI" ,
                        "Port Moresby,Papua" ,
                        "Port of Spain,Trinida" ,
                        "Port Salerno,FL" ,
                        "Port Sulphur,LA" ,
                        "Port-au-Prince,Haiti" ,
                        "Portland,ME" ,
                        "Portland,OR" ,
                        "Portsmouth,England" ,
                        "Portsmouth,NH" ,
                        "Portsmouth,OH" ,
                        "Portsmouth,VA" ,
                        "Potomac,MD" ,
                        "Pottstown,PA" ,
                        "Poughkeepsie,NY" ,
                        "Prague,Czech" ,
                        "Pratt,KS" ,
                        "Prescott,AZ" ,
                        "Preston,ID" ,
                        "Pretoria,S._Africa" ,
                        "Primghar,IA" ,
                        "Prince Albert,SK" ,
                        "Prince George,BC" ,
                        "Prince Rupert,BC" ,
                        "Princeton,MO" ,
                        "Princeton,NJ" ,
                        "Princeton,WV" ,
                        "Proctor,VT" ,
                        "Prosser,WA" ,
                        "Providence,RI" ,
                        "Provo,UT" ,
                        "Prudhoe Bay,AK" ,
                        "Pueblo,CO" ,
                        "Puerto Montt,Chile" ,
                        "Puerto Real,PR" ,
                        "Putnam,CT" ,
                        "Puyallup,WA" ,
                        "Punta Cana,Dominican",



                        "Quakertown,PA" ,
                        "Quebec,PQ" ,
                        "Quincy,MA" ,
                        "Quito,Ecuador" ,

                        "Raanana,Israel" ,
                        "Rabat,Morocco" ,
                        "Racine,WI" ,
                        "Raleigh,NC" ,
                        "Ramstein_AB,Germany" ,
                        "Randolph,VT" ,
                        "Rangeley,ME" ,
                        "Rangoon,Myanmar" ,
                        "Rapid_City,SD" ,
                        "Rawalpindi,Pakistan" ,
                        "Rawlins,WY" ,
                        "Reading,PA" ,
                        "Recife,Brazil" ,
                        "Redding,CA" ,
                        "Redondo Beach,CA" ,
                        "Redwood City,CA" ,
                        "Regensburg,Germany" ,
                        "Regina,SK" ,
                        "Reims,France" ,
                        "Rennes,France" ,
                        "Reno,NV" ,
                        "Reseda,CA" ,
                        "Rexburg,ID" ,
                        "Reykjavik,Iceland" ,
                        "Rhinelander,WI" ,
                        "Richardson,TX" ,
                        "Richland,WA" ,
                        "Richmond,Australia" ,
                        "Richmond,CA" ,
                        "Richmond,KY" ,
                        "Richmond,UT" ,
                        "Richmond,VA" ,
                        "Rifle,CO" ,
                        "Rio de Janeiro,Brazil" ,
                        "Riverside,CA" ,
                        "Riverton,WY" ,
                        "Riyadh,Saudi Arabia" ,
                        "Roanoke,VA" ,
                        "Robinson,IL" ,
                        "Rochdale,Lanc,England" ,
                        "Rochester Hills,MI" ,
                        "Rochester,MN" ,
                        "Rochester,NH" ,
                        "Rochester,NY" ,
                        "Rock Hill,SC" ,
                        "Rock Springs,WY" ,
                        "Rockford,IL" ,
                        "Rockland,ME" ,
                        "Rockport,MO" ,
                        "Rockville,MD" ,

                        "Rockwood,ME" ,
                        "Rocky Mount,NC" ,
                        "Rogers,AR" ,
                        "Rome,Italy" ,
                        "Roosevelt_Roads,PR" ,
                        "Rosemead,CA" ,
                        "Roseville,CA" ,
                        "Roseville,MI" ,
                        "Rostock,Germany" ,
                        "Roswell,GA" ,
                        "Roswell,NM" ,
                        "Rotterdam,Netherlands" ,
                        "Rouen,France" ,
                        "Roundup,MT" ,
                        "Rowland Heights,CA" ,
                        "Royal Oak,MI" ,
                        "Ruby,AK" ,
                        "Rugby,ND" ,
                        "Rumford,RI" ,
                        "Russell,KS" ,
                        "Ruston,LA" ,
                        "Rutland,VT" ,

                        "S._Portland,ME" ,
                        "Saco,ME" ,
                        "Sacramento,CA" ,

                        "Saginaw,MI" ,
                        "Saginaw,TX" ,

                        "Sale,Australia" ,
                        "Salem,MA" ,
                        "Salem,NH" ,
                        "Salem,OR" ,
                        "Salem,WV" ,
                        "Salina,KS" ,
                        "Salina,UT" ,
                        "Salinas,CA" ,
                        "Salisbury,MD" ,
                        "Sallisaw,OK" ,
                        "Salmon,ID" ,
                        "Salt_Lake_City,UT" ,
                        "Salton_City,CA" ,
                        "Salzburg,Austria" ,
                        "Samarrah,Iraq" ,
                        "San Angelo,TX" ,
                        "San Antonio,TX" ,
                        "San Antonio,TX" ,
                        "San Bernardino,CA" ,
                        "San Diego,CA" ,
                        "San Francisco,CA" ,
                        "San Jose,CA" ,
                        "San Jose,Costa_Rica" ,
                        "San Juan,PR" ,
                        "San Leandro,CA" ,
                        "San Mateo,CA" ,
                        "San Pedro,CA" ,
                        "San Salvador,El_Salv." ,
                        "Sanders,AZ" ,
                        "Sandersville,GA" ,
                        "Sandhurst,Surry,ENG" ,
                        "Sandpoint,ID" ,
                        "Sanford,ME" ,
                        "Santa Ana,CA" ,
                        "Santa Barbara,CA" ,
                        "Santa Clara,CA" ,
                        "Santa Cruz,Bolivia" ,
                        "Santa Fe,NM" ,
                        "Santa Maria,CA" ,
                        "Santa Monica,CA" ,
                        "Santa Rosa,CA" ,
                        "Santa Rosa,NM" ,
                        "Santiago,Chile" ,
                        "Santo Domingo,Dom._Re" ,
                        "Sao Paulo,Brazil" ,
                        "Sapporo,Japan" ,
                        "Sarajevo,Bosnia" ,
                        "Sarasota,FL" ,
                        "Sargent,NE" ,
                        "Saskatoon,Sask." ,
                        "Sault_Ste._Marie,MI" ,
                        "Savannah,GA" ,
                        "Sharm el Sheikh,Egypt",
                        "Scarborough,ON" ,
                        "Schaumburg,IL" ,
                        "Schenectady,NY" ,
                        "Schuyler,NE" ,
                        "Scottsdale,AZ" ,
                        "Scranton,PA" ,
                        "Seabrook,TX" ,
                        "Seaford,DE" ,
                        "Seal Beach,CA" ,
                        "Seattle,WA" ,
                        "Sebastian,FL" ,
                        "Selma,AL" ,
                        "Selter,Germany" ,
                        "Seoul,S._Korea" ,
                        "Sept-Iles,PQ" ,
                        "Seville,Spain" ,
                        "Seward,AK" ,

                        "Seymour,TN" ,
                        "Shanghai,China" ,
                        "Shannon,Ireland" ,
                        "Shawnee,KS" ,
                        "Sharjah,UAE",
                        "Sheboygan,WI" ,
                        "Sheffield,England" ,
                        "Shenzhen,China",
                        "Shelby,OH" ,
                        "Shelbyville,TN" ,
                        "Sheldon,IA" ,
                        "Shell Beach,CA" ,
                        "Shemya,AK" ,
                        "Sherbrooke,PQ" ,
                        "Sheridan,WY" ,
                        "Shiraz,Iran" ,
                        "Shoshone,ID" ,
                        "Shreveport,LA" ,
                        "Shungnak,AK" ,
                        "Sibu,Malaysia" ,
                        "Sigonella,Sicily" ,
                        "Silver Spring,MD" ,
                        "Simi Valley,CA" ,
                        "Singapore" ,
                        "Siem Reap,Siem Reap",
                        "Sioux City,IA" ,
                        "Sioux Falls,SD" ,
                        "Sioux Lookout,ON" ,
                        "Sioux Narrows,ON" ,
                        "Sitka,AK" ,
                        "Sittwe,Myanmar" ,
                        "Skokie,IL" ,
                        "Slidell,LA" ,
                        "Smyrna,DE" ,
                        "Soda Springs,ID" ,
                        "Soeborg,Denmark" ,
                        "Sofia,Bulgaria" ,
                        "Somerset,KY" ,
                        "Somerset,NJ" ,
                        "Somerville,MA" ,
                        "Sousse,Tunisia",

                        "Somerville,NJ" ,
                        "Sondrestrom,Gnld." ,
                        "Sonoma,CA" ,
                        "South Bend,IN" ,
                        "South Gate,CA" ,
                        "South Kauai VORTAC,HI" ,
                        "Southampton,England" ,
                        "Southampton,NY" ,
                        "Southfield,MI" ,
                        "Southington,CT" ,
                        "Sparks,NV" ,
                        "Spartanburg,SC" ,
                        "Spenard,AK" ,
                        "Spencer,IA" ,
                        "Spokane,WA" ,
                        "Springdale,AR" ,
                        "Springfield,IL" ,
                        "Springfield,MA" ,
                        "Springfield,MO" ,
                        "Springfield,OH" ,
                        "Springfield,OR" ,
                        "Springfield,VT" ,
                        "St-Hubert,Quebec" ,
                        "St._Albans,VT" ,
                        "St._Catherines,ON" ,
                        "St._Charles,MO" ,
                        "St._Clair_Shores,MI" ,
                        "St._Cloud,MN" ,
                        "St._Croix,VI" ,
                        "St._George,UT" ,
                        "St._John's,Nfld." ,
                        "St._John,NB" ,
                        "St._Joseph,MO" ,
                        "St._Louis_Park,MN" ,
                        "St._Louis,MO" ,
                        "St._Michales,MD" ,
                        "St._Nazaire,France" ,
                        "St._Paul,MN" ,
                        "St._Petersburg,FL" ,
                        "St._Petersburg,Russia" ,
                        "St._Thomas,VI" ,
                        "Stamford,CT" ,
                        "Stanley,Falkland_Is." ,
                        "Staten_Island,NY" ,
                        "Statesville,NC" ,
                        "Steamboat_Springs,CO" ,
                        "Sterling_Heights,MI" ,
                        "Sterling,IL" ,
                        "Sterling,VA" ,
                        "Steubenville,OH" ,
                        "Stockholm,ME" ,
                        "Stockholm,Sweden" ,
                        "Stockton,CA" ,
                        "Stony Brook,NY" ,
                        "Strasbourg,France" ,
                        "Stratford,CT" ,
                        "Sturtevant,WI" ,
                        "Stuttgart,Germany" ,
                        "Sudbury,ON" ,
                        "Suffolk,VA" ,
                        "Sumter,SC" ,
                        "Suzhou,China",
                        "Sun Valley,CA" ,
                        "Sunnyvale,CA" ,
                        "Sunrise,FL" ,
                        "Superior,WI" ,
                        "Swannanoa,NC" ,
                        "Swift Current,Sask." ,
                        "Sydney,Australia" ,
                        "Sydney,NS" ,
                        "Syracuse,NY" ,
                        "Tabriz,Iran" ,
                        "Tacoma,WA" ,
                        "Tai Tam,Hong_Kong" ,
                        "Taipei,Taiwan" ,
                        "Talara,Peru" ,
                        "Tallahassee,FL" ,
                        "Tampa,FL" ,
                        "Tangier,Morocco" ,
                        "Taylor,MI" ,
                        "Tegucigalpa,Honduras" ,
                        "Tehran,Iran" ,
                        "Teignmouth,England" ,
                        "Tel Aviv,Israel" ,
                        "Tempe,AZ" ,
                        "Tengah,Singapore" ,
                        "Tenino,WA" ,
                        "Tern Island,HI" ,
                        "Terre Haute,IN" ,
                        "Texarkana,AR" ,
                        "Tennessee",
                        "Texarkana,TX" ,
                        "Texas",
                        "The Pas,MB" ,
                        "Thibodaux,LA" ,
                        "Thomasville,AL" ,
                        "Thornton,CO" ,
                        "Thousand_Oaks,CA" ,
                        "Thule,Greenland" ,
                        "Thunder_Bay,ON" ,
                        "Tifton,GA" ,
                        "Tillson,NY" ,
                        "Timmins,ON" ,
                        "Tinak,Marshall_Is." ,
                        "Tokyo,Japan" ,
                        "Toledo,OH" ,
                        "Tombstone,AZ" ,
                        "Topeka,KS" ,
                        "Toronto,ON" ,
                        "Torrance,CA" ,
                        "Torrington,CT" ,
                        "Toulouse,France" ,
                        "Tours,France" ,
                        "Townsville,Australia" ,
                        "Trapani,Sicily" ,
                        "Traverse_City,MI" ,
                        "Trenton,NJ" ,
                        "Trinidad,CO" ,
                        "Tripoli,Libya" ,
                        "Trois-Rivieres,PQ" ,
                        "Troy,MI" ,
                        "Troy,MT" ,
                        "Troy,NY" ,
                        "Truk Atoll,Micronesia" ,

                        "Tucker,GA" ,
                        "Tucson,AZ" ,
                        "Tucumcari,NM" ,
                        "Tulsa,OK" ,
                        "Tunis,Tunisia" ,
                        "Tupelo,MS" ,
                        "Tuscaloosa,AL" ,
                        "Twin_Falls,ID" ,
                        "Tyler,TX" ,

                        "Ubon,Thailand" ,
                        "Udon-Thani,Thailand" ,
                        "Uelzen,Germany" ,
                        "Ujung_Pandang,Indones" ,
                        "Unalaska,AK" ,
                        "Union City,NJ" ,
                        "Union City,TN" ,
                        "University City,MO" ,
                        "Upolu Point,HI" ,
                        "Upolu,HI" ,
                        "Urbana,IL" ,
                        "Utica,NY" ,
                        "Utirik,Marshall_Is." ,

                        "Vacaville,CA" ,
                        "Valencia,ES" ,
                        "Val-d'or,PQ" ,
                        "Valdez,AK" ,
                        "Valdosta,GA" ,
                        "Vale,OR" ,
                        "Valentine,NE" ,
                        "Valhalla,NY" ,
                        "Vallejo,CA" ,
                        "Valletta,Malta" ,
                        "Valparaiso,Chile" ,
                        "Van Buren,ME" ,
                        "Van Nuys,CA" ,
                        "Vancouver,BC" ,
                        "Vancouver,WA" ,
                        "Vandans,Austria" ,
                        "Vandenberg_AFB,CA" ,
                        "Vaughn,NM" ,
                        "Venice,CA" ,
                        "Venice,Italy" ,
                        "Ventura,CA" ,
                        "Vermillion,SD" ,
                        "Vernal,UT" ,
                        "Vicksburg,MS" ,
                        "Victoria,BC" ,
                        "Victoria,TX" ,
                        "Vienna,Austria" ,
                        "Vineland,NJ" ,
                        "Virginia Beach,VA" ,
                        "Virginia Beach,VA" ,
                        "Visalia,CA" ,
                        "Vladivostok,Russia" ,
                        "Vols,Austria",
                        "W._Fargo,ND" ,
                        "W._Hartford,CT" ,
                        "W._Springfield,MA" ,
                        "W._Warwick,RI" ,
                        "Wabash,IN" ,
                        "Waco,TX" ,
                        "Wahiawa,HI" ,
                        "Waialua,HI" ,
                        "Waikola,HI" ,
                        "Wailuku,HI" ,
                        "Waimea,HI" ,
                        "Waipahu,HI" ,
                        "Wakefield,MA" ,
                        "Waldoboro,ME" ,
                        "Walker,LA" ,
                        "Walla Walla,WA" ,
                        "Wallace,ID" ,
                        "Wallowa,OR" ,
                        "Walnut Creek,CA" ,
                        "Waltham,MA" ,
                        "Warner Robins,GA" ,
                        "Warren,MI" ,
                        "Warren,OH" ,
                        "Warren,PA" ,
                        "Warsaw,Poland" ,
                        "Warwick,RI" ,
                        "Wasco,OR" ,
                        "Waseca,MN" ,
                        "Washington_(USNO),DC" ,
                        "Washington,DC" ,
                        "Washington,IL" ,
                        "Waterbury,CT" ,
                        "Waterloo,IA" ,
                        "Waterloo,ON" ,
                        "Watertown,NY" ,
                        "Watertown,SD" ,
                        "Waterville,WA" ,
                        "Waukegan,IL" ,
                        "Waukesha,WI" ,
                        "Wausau,WI" ,
                        "Wauwatosa,WI" ,
                        "Waycross,GA" ,
                        "Wayne,NE" ,
                        "Waynesboro,VA" ,
                        "Waynesburg,PA" ,
                        "Weirs,NH" ,
                        "Weirton,WV" ,
                        "Wellington" ,
                        "Wells,NV" ,
                        "Wendover,UT" ,
                        "West Allis,WI" ,
                        "West Covina,CA" ,
                        "West Haven,CT" ,
                        "West Hills,CA" ,
                        "West Memphis,AR" ,
                        "West Palm Beach,FL" ,
                        "Westbrook,ME" ,
                        "Westerly,RI" ,
                        "Westland,MI" ,
                        "Westminster,CA" ,
                        "Westminster,CO" ,
                        "Westminster,MD" ,
                        "Westover AFB,MA" ,
                        "Weymouth,MA" ,
                        "Wheaton,MD" ,
                        "Wheeler AFB,HI" ,
                        "Wheeling,WV" ,
                        "Whenuapai,New Zealand" ,
                        "Whidbey Is.,WA" ,
                        "White Plains,NY" ,
                        "Whitehorse,Yukon" ,
                        "Whittier,CA" ,
                        "Wichita Falls,TX" ,
                        "Wichita,KS" ,
                        "Wickenburg,AZ" ,
                        "Wilder,ID" ,
                        "Wilkes-Barre,PA" ,
                        "Willcox,AZ" ,
                        "Williston,ND" ,
                        "Wilmington,DE" ,
                        "Wilmington,NC" ,
                        "Winchester,ID" ,
                        "Winchester,KY" ,
                        "Winchester,NH" ,
                        "Winchester,VA" ,
                        "Windam,CT" ,
                        "Windsor,ON" ,
                        "Winnemucca,NV" ,
                        "Winner,SD" ,
                        "Winnett,MT" ,
                        "Winnfield,LA" ,
                        "Winnipeg,MB" ,
                        "Winona,MN" ,
                        "Winona,MS" ,
                        "Winooski,VT" ,
                        "Winsted,CT" ,
                        "Winston-Salem,NC" ,
                        "Wolphaartsdijk,Neth." ,
                        "Woodland_Hills,CA" ,
                        "Woodsville,NH" ,
                        "Woodward,OK" ,
                        "Woonsocket,RI" ,
                        "Woonsock et,SD" ,
                        "Worcester,MA" ,
                        "Wotje,Marshall_Is." ,

                        "Wurzburg,Germany" ,
                        "Wynnewood,PA" ,
                        "Wyoming,MI" ,
                        "Wytheville,VA" ,

                        "Yakima,WA" ,
                        "Yakutat,AK" ,
                        "Yalta,Ukraine" ,
                        "Yankton,SD" ,
                        "Yap Island,Micronesia" ,
                        "Yardley,PA" ,
                        "Yellowknife,NWT" ,
                        "Yonkers,NY" ,
                        "York,PA" ,
                        "Yorktown Heights,NY" ,
                        "Youngstown,OH" ,
                        "Yuba City,CA" ,
                        "Yuma,AZ" ,
                        "Yuma,CO" ,
                        "Zanesville,OH" ,
                        "Zaragoza,Spain" ,
                        "Zhuhai,China",
                        "Zurich,Switzerland" ,
                        "Zwickau,Germany"
                };

                return AllCity;
        }

}